ALTER TABLE profiles
  ADD COLUMN IF NOT EXISTS city        TEXT DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS school      TEXT DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS job         TEXT DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS zodiac      TEXT DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS music_taste TEXT DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS party_style TEXT DEFAULT NULL;
